// ─── Leave Form Styles ────────────────────────────────────────────────────────

const brandRed = '#9b1c31';
const brandYellow = '#ffcc00';

const leaveFormStyles = {
  container: {
    width: '100%',
    padding: '1.5rem',
    background: 'transparent',
    minHeight: '100%',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    background: 'white',
    padding: '1.5rem 2rem',
    borderRadius: '28px',
    boxShadow: '0 10px 25px -10px rgba(155, 28, 49, 0.05)',
    border: '2px solid #f1f5f9',
  },
  titleSection: {
    flex: 1,
  },
  title: {
    fontSize: '2rem',
    fontWeight: '900',
    color: '#1A202C',
    marginBottom: '0.25rem',
    letterSpacing: '-0.025em',
  },
  breadcrumbs: {
    display: 'flex',
    gap: '0.5rem',
    color: '#94a3b8',
    fontSize: '0.85rem',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  notificationBell: {
    position: 'relative',
    cursor: 'pointer',
    color: brandRed,
    background: '#fff0f2',
    padding: '0.75rem',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: '-3px',
    right: '-3px',
    background: brandYellow,
    color: brandRed,
    fontWeight: '900',
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    fontSize: '0.65rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid white',
  },
  adminName: {
    fontWeight: '900',
    display: 'block',
    color: '#1A202C',
    fontSize: '0.95rem',
  },
  adminRole: {
    fontSize: '0.75rem',
    color: '#64748b',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '16px',
    objectFit: 'cover',
    boxShadow: '0 4px 10px rgba(155, 28, 49, 0.15)',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1.5rem',
    marginBottom: '1.5rem',
  },
  statCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '28px',
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    boxShadow: '0 10px 25px -10px rgba(155, 28, 49, 0.05)',
    border: '2px solid #f1f5f9',
    transition: 'all 0.3s ease',
  },
  statCardTotal: { borderColor: 'transparent' },
  statCardPending: { borderColor: 'transparent' },
  statCardApproved: { borderColor: 'transparent' },
  statCardRejected: { borderColor: 'transparent' },
  statIcon: {
    width: '56px',
    height: '56px',
    borderRadius: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    boxShadow: 'inset 0 2px 4px rgba(255,255,255,0.5), 0 4px 10px rgba(0,0,0,0.05)'
  },
  statIconTotal: { background: 'linear-gradient(135deg, #1e293b, #334155)', color: 'white' },
  statIconPending: { background: `linear-gradient(135deg, ${brandYellow}, #fbbf24)`, color: brandRed },
  statIconApproved: { background: 'linear-gradient(135deg, #10b981, #34d399)', color: 'white' },
  statIconRejected: { background: `linear-gradient(135deg, ${brandRed}, #e11d48)`, color: 'white' },
  statCount: {
    fontSize: '1.75rem',
    fontWeight: '900',
    display: 'block',
    color: '#1A202C',
    letterSpacing: '-0.025em',
  },
  statLabel: {
    fontSize: '0.8rem',
    color: '#64748b',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  filtersSection: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '28px',
    marginBottom: '1.5rem',
    boxShadow: '0 10px 25px -10px rgba(155, 28, 49, 0.05)',
    border: '2px solid #f1f5f9',
  },
  searchRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    gap: '1rem',
  },
  searchBar: {
    flex: 1,
    position: 'relative',
  },
  searchInput: {
    width: '100%',
    padding: '0.85rem 1.25rem 0.85rem 3rem',
    background: '#f8fafc',
    border: '2px solid transparent',
    borderRadius: '20px',
    outline: 'none',
    fontFamily: 'inherit',
    fontWeight: '600',
    fontSize: '0.9rem',
    color: '#1e293b',
    transition: 'all 0.2s',
  },
  searchIcon: {
    position: 'absolute',
    left: '1.25rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
  },
  filterRow: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  filterInput: {
    padding: '0.75rem 1.25rem',
    background: '#f8fafc',
    border: '2px solid transparent',
    borderRadius: '16px',
    outline: 'none',
    minWidth: '160px',
    fontFamily: 'inherit',
    fontWeight: '600',
    fontSize: '0.85rem',
    color: '#475569',
    cursor: 'pointer',
  },
  btnFilter: {
    background: brandYellow,
    color: brandRed,
    padding: '0.75rem 1.5rem',
    borderRadius: '16px',
    border: 'none',
    fontWeight: '800',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    boxShadow: `0 4px 10px rgba(255, 204, 0, 0.4)`,
    transition: 'transform 0.2s',
  },
  tableContainer: {
    background: 'white',
    borderRadius: '28px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    msOverflowStyle: 'none',
    boxShadow: '0 10px 25px -10px rgba(155, 28, 49, 0.05)',
    border: '2px solid #f1f5f9',
    marginBottom: '2rem',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    minWidth: '1400px',
  },
  thead: {
    background: '#f8fafc',
    borderBottom: '2px solid #f1f5f9',
  },
  th: {
    textAlign: 'left',
    padding: '1.25rem 1.5rem',
    fontSize: '0.75rem',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: '#64748b',
    whiteSpace: 'nowrap',
  },
  td: {
    padding: '1.25rem 1.5rem',
    borderBottom: '1px solid #f1f5f9',
    verticalAlign: 'middle',
    fontSize: '0.9rem',
    color: '#334155',
    whiteSpace: 'nowrap',
  },
  facultyCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    minWidth: '220px',
  },
  facultyImg: {
    width: '44px',
    height: '44px',
    borderRadius: '14px',
    objectFit: 'cover',
    background: '#f1f5f9',
    border: '2px solid white',
    boxShadow: '0 2px 5px rgba(0,0,0,0.05)',
  },
  statusBadge: {
    padding: '0.4rem 1rem',
    borderRadius: '20px',
    fontSize: '0.75rem',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    display: 'inline-block',
  },
  statusPending: { background: '#fffbeb', color: '#b45309', border: '1px solid #fef3c7' },
  statusApproved: { background: '#ecfdf5', color: '#047857', border: '1px solid #d1fae5' },
  statusRejected: { background: '#fff1f2', color: '#be123c', border: '1px solid #ffe4e6' },
  actionBtns: {
    display: 'flex',
    gap: '0.5rem',
  },
  btnTable: {
    padding: '0.5rem 0.75rem',
    borderRadius: '12px',
    border: '2px solid transparent',
    background: '#f8fafc',
    color: '#475569',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    transition: 'all 0.2s',
  },
  btnApprove: { background: '#ecfdf5', color: '#047857', borderColor: '#ecfdf5' },
  btnReject: { background: '#fff1f2', color: '#be123c', borderColor: '#fff1f2' },
  pagination: {
    padding: '1.25rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.85rem',
    fontWeight: '600',
    color: '#64748b',
    background: '#f8fafc',
  },
  reportsGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 2fr) minmax(0, 1.5fr) minmax(0, 1fr)',
    gap: '1.5rem',
    margin: '0',
    paddingBottom: '2rem'
  },
  reportCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '28px',
    boxShadow: '0 10px 25px -10px rgba(155, 28, 49, 0.05)',
    border: '2px solid #f1f5f9',
    display: 'flex',
    flexDirection: 'column',
  },
  reportTitle: {
    fontSize: '1rem',
    marginBottom: '1.25rem',
    color: '#1A202C',
    fontWeight: '800',
    letterSpacing: '-0.01em',
  },
  downloadReport: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
    flex: 1,
    justifyContent: 'center'
  },
  btnDownload: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.85rem',
    borderRadius: '16px',
    border: '2px solid transparent',
    background: '#f8fafc',
    fontWeight: '800',
    fontSize: '0.85rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
};

export default leaveFormStyles;
