// ─── Leave Form Styles ────────────────────────────────────────────────────────

const leaveFormStyles = {
  container: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '2rem',
    backgroundColor: '#fafafa',
    minHeight: '100vh',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
  },
  titleSection: {
    flex: 1,
  },
  title: {
    fontSize: '1.75rem',
    fontWeight: '700',
    color: '#d32f2f',
    marginBottom: '0.5rem',
  },
  breadcrumbs: {
    display: 'flex',
    gap: '0.5rem',
    color: '#757575',
    fontSize: '0.9rem',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  notificationBell: {
    position: 'relative',
    cursor: 'pointer',
    fontSize: '1.5rem',
  },
  notificationDot: {
    position: 'absolute',
    top: '-5px',
    right: '-5px',
    background: '#d32f2f',
    color: 'white',
    borderRadius: '50%',
    width: '18px',
    height: '18px',
    fontSize: '0.7rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminName: {
    fontWeight: '700',
    display: 'block',
  },
  adminRole: {
    fontSize: '0.8rem',
    color: '#757575',
  },
  avatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  statCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    borderLeft: '5px solid',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  statCardTotal:    { borderColor: '#2196f3' },
  statCardPending:  { borderColor: '#ffc107' },
  statCardApproved: { borderColor: '#2e7d32' },
  statCardRejected: { borderColor: '#d32f2f' },
  statIcon: {
    width: '50px',
    height: '50px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
  },
  statIconTotal:    { background: '#e3f2fd', color: '#2196f3' },
  statIconPending:  { background: '#fff8e1', color: '#ffc107' },
  statIconApproved: { background: '#e8f5e9', color: '#2e7d32' },
  statIconRejected: { background: '#ffebee', color: '#d32f2f' },
  statCount: {
    fontSize: '1.5rem',
    fontWeight: '800',
    display: 'block',
  },
  statLabel: {
    fontSize: '0.9rem',
    color: '#757575',
  },
  filtersSection: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '12px',
    marginBottom: '1.5rem',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  },
  searchRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    gap: '1rem',
  },
  searchBar: {
    flex: 1,
    position: 'relative',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.5rem',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    outline: 'none',
    fontFamily: 'inherit',
  },
  searchIcon: {
    position: 'absolute',
    left: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#757575',
  },
  filterRow: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  filterInput: {
    padding: '0.6rem 1rem',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    outline: 'none',
    minWidth: '150px',
    fontFamily: 'inherit',
  },
  btnFilter: {
    background: '#ffc107',
    color: '#212121',
    padding: '0.6rem 1.5rem',
    borderRadius: '8px',
    border: 'none',
    fontWeight: '600',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  tableContainer: {
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    marginBottom: '2rem',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  thead: {
    background: '#f8f9fa',
    borderBottom: '1px solid #e0e0e0',
  },
  th: {
    textAlign: 'left',
    padding: '1rem',
    fontSize: '0.85rem',
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#757575',
  },
  td: {
    padding: '1rem',
    borderBottom: '1px solid #e0e0e0',
    verticalAlign: 'middle',
  },
  facultyCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  facultyImg: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    objectFit: 'cover',
    background: '#eee',
  },
  statusBadge: {
    padding: '0.4rem 0.8rem',
    borderRadius: '20px',
    fontSize: '0.8rem',
    fontWeight: '600',
    display: 'inline-block',
  },
  statusPending:  { background: '#fff8e1', color: '#ef6c00', border: '1px solid #ffe082' },
  statusApproved: { background: '#e8f5e9', color: '#2e7d32', border: '1px solid #a5d6a7' },
  statusRejected: { background: '#ffebee', color: '#d32f2f', border: '1px solid #ef9a9a' },
  actionBtns: {
    display: 'flex',
    gap: '0.5rem',
  },
  btnTable: {
    padding: '0.4rem 0.8rem',
    borderRadius: '6px',
    border: '1px solid #e0e0e0',
    background: 'white',
    cursor: 'pointer',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    transition: 'all 0.2s',
  },
  btnApprove: { color: '#2e7d32', borderColor: '#2e7d32' },
  btnReject:  { color: '#d32f2f', borderColor: '#d32f2f' },
  pagination: {
    padding: '1rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '0.9rem',
    borderTop: '1px solid #e0e0e0',
  },
  reportsGrid: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    gap: '1.5rem',
    marginTop: '2rem',
  },
  reportCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
  },
  reportTitle: {
    fontSize: '1.1rem',
    marginBottom: '1rem',
    color: '#212121',
    fontWeight: '600',
  },
  pendingList: {
    listStyle: 'none',
  },
  pendingListItem: {
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
    fontSize: '0.9rem',
  },
  downloadReport: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  btnDownload: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    borderRadius: '8px',
    border: '1px solid #e0e0e0',
    background: 'white',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
};

export default leaveFormStyles;
